title: Diogo Rodrigues
email: dmfrodrigues2000@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  travels:
    output: true

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  social_links:
    - {
        platform: facebook,
        user: diogomfr,
        user_url: "https://www.facebook.com/diogomfr",
      }
    - {
        platform: github,
        user: dmfrodrigues,
        user_url: "https://github.com/dmfrodrigues",
      }
    - {
        platform: linkedin,
        user: dmfrodrigues,
        user_url: "https://www.linkedin.com/in/dmfrodrigues",
      }
    - {
        platform: spotify,
        user: dmfrodrigues2000,
        user_url: "https://open.spotify.com/user/dmfrodrigues2000",
      }
#
# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

